name: Deploy
on: [ push, workflow_dispatch ]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Getcode
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run test
    - name: Build
      run: npm run build
    - name: Deploy
      run: echo "Deploying..."
